# Generated by Django 6.0.6 on 2026-06-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followercount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCount',
            new_name='FollowersCount',
        ),
    ]
